### ISSUE TITLE
"Ticker" library by Bert Melis meanwhile merged into the ESP32 Arduino core...

### ISSUE THREAD

**Issue by dl9sec** [ElektorLabs/180662-mini-NTP-ESP32#2]
The "Ticker" library by Bert Melis has been merged into the Arduino ESP32 core (see https://github.com/bertmelis/Ticker-esp32), so there is no need to include it into the libraries directory. You will not find it in the library manager...

**Comment by lab-mathias-claussen** [comment]
Hi dl9sec,

thanks for the information, we will update the code soon and remove the includes for the library. 

Best Regards

CalM

**Comment by lab-mathias-claussen** [comment]
Includes need to stay, but library no longer mentioned as dependency

**Comment by dl9sec** [comment]
Deleted in the sources, but not in the README.md :-)
