### ISSUE TITLE
License of the firmware?

### ISSUE THREAD

**Issue by dl9sec** [ElektorLabs/180662-mini-NTP-ESP32#4]
What is the license of the firmware?

Regards, Thorsten

**Comment by lab-mathias-claussen** [comment]
Hi dl9sec,

license will be added soon, we will change to GPLv3 for the code in the repository. This sould be compatible with the license used by the external librarys 

Regards

**Comment by dl9sec** [comment]
tnx.
Concerning the additional libraries, which are MIT/BSD and LGPL-2.1, GPL-3.0 should be ok, but no idea, if all the other "standard" libraries are compatible...

Regards, Thorsten

**Comment by lab-mathias-claussen** [comment]
License has changed to GPLv3 for the code. As far as we can see providing binary files may be a problem

**Comment by dl9sec** [comment]
> License has changed to GPLv3 for the code. As far as we can see providing binary files may be a problem

Maybe not a problem, but a lot of work (collect all the licences, copyrights, disclaimers and (L)GPLed sources of all linked libraries). Does it really make sense to provide binaries for a project in an Arduino ecosystem?

**Comment by dl9sec** [comment]
I would suggest to put the license file as LICENSE to the sources to fulfill the GPL.

**Comment by lab-mathias-claussen** [comment]
Hi dl9sec,

from what we can see : https://www.gnu.org/licenses/gpl-howto.html
the fileshould be "Add a COPYING file with a copy of the GNU GPL or GNU AGPL"

we can also include a LICENSE file

**Comment by dl9sec** [comment]
Perfect 👍
