### ISSUE TITLE
GPS week number rollover fix doesn't work

### ISSUE THREAD

**Issue by dl9sec** [ElektorLabs/180662-mini-NTP-ESP32#5]
Hi Mathias,

thank you very much for your really great and quick implementation of the rollover fix and your efforts.

Yesterday I tested the new code, but it doesn't seem to work. Although the rollover count is set to 1, the date from the NMEA stream is shown (without addition of the 1024 weeks).

I took a look at the code today:

       if(gps_config.rollover_cnt>0){

              newtimestamp + (  SECS_PER_WEEK * 1024 *gps_config.rollover_cnt );
       }

Could it be, that there is a "=" missing?

       if(gps_config.rollover_cnt>0){

              newtimestamp += (  SECS_PER_WEEK * 1024 *gps_config.rollover_cnt );
       }

I will try it later this day...

Regards, Thorsten

**Comment by lab-mathias-claussen** [comment]
Code has been patch and should work now
