### ISSUE TITLE
Link to the article at README.md is broken

### ISSUE THREAD

**Issue by dl9sec** [ElektorLabs/180662-mini-NTP-ESP32#6]
The Link at the bottom of README.md (https://www.elektormagazine.com/labs/admin-preview/mini-ntp-server-with-gps) seems to be a preview link and is now broken.

Should be https://www.elektormagazine.com/labs/mini-ntp-server-with-gps

**Comment by lab-mathias-claussen** [comment]
Readme.md has now working link
