### ISSUE TITLE
Source code from 180622_1_3-11.zip can not be built

### ISSUE THREAD

**Issue by dl9sec** [ElektorLabs/180662-mini-NTP-ESP32#7]
The source code in 180622_1_3-11.zip downloadable from https://www.elektormagazine.com/labs/mini-ntp-server-with-gps can not be build because of a (residual) "network.ino" (seems to be an old version of network.cpp).
File must be deleted to make the code buildable.

**Comment by lab-mathias-claussen** [comment]
Hi dl9sec,

Labs page has been updated to 1.4

Regards
