### ISSUE TITLE
Can't compile

### ISSUE THREAD

**Issue by cyber-junkie9** [ElektorLabs/180662-mini-NTP-ESP32#8]
I am not able to compile latest version , download from github only

error - redefinition of 'class NTP_Server'
using ESP32 nodemcu (Dev kit V1) with Arduino IDE

edit -

after downgrading arduino json lib it showing another error 

conversion from 'int' to 'DateTime' is ambiguous

if possible please upload pre-compiled binary file too...

**Comment by lab-mathias-claussen** [comment]
Hi tech-freak,

we will look into this issue, it seems that something in the IDF and / or library has changed and causes conflicts for now. 
Pre compiled binarys are technically doable but due to the way they are licensed will cause trouble in the end for compiled binarys so we need to check the legal stuff first

Best Regards

Mathias Claußen

**Comment by tech-freak** [comment]
Okay , i'll wait then and by any chance any port available for ESP8266 ?

**Comment by lab-mathias-claussen** [comment]
Hi tech-freak,

for the ESP826 this means a bunch of components need to be changed an all the RTOS parts need to be removed. Yes, it can be done, but has no high priority.

Best Regards

Mathias Claußen

**Comment by tech-freak** [comment]
okay.
i again updated all lib and tried to compile ,i was still getting error 


changed line 
[686](https://github.com/ElektorLabs/180662-mini-NTP-ESP32/blob/master/Firmware/Firmware.ino#L686)
from
  DateTime now = 0;
to
  DateTime now;
and now it compiles and works perfectly

**Comment by tech-freak** [comment]
also by any chance can you add option to add online NTP server and sync to RTC ? 
so who don't want to use GPS and still want offline server with ESP32+RTC can use it (those who don't have stable internet )

**Comment by lab-mathias-claussen** [comment]
Moved code to PlatformIO and fixed dependencys for compilation
Next step may be to move to ESP32-C3
Will close this one
